### ISSUE TITLE
Add transpile only version?

### ISSUE THREAD

**Issue by RebeccaStevens** [luanglopes/ts-paths-esm-loader#1]
Could we get a version that uses `ts-node/esm/transpile-only` instead of `ts-node/esm`.

Ideally loaded via `ts-paths-esm-loader/transpile-only`.

**Comment by RebeccaStevens** [comment]
man, you're fast 😄

**Comment by luanglopes** [comment]
@RebeccaStevens thanks for it, just published a new version to NPM with the command on readme
