### ISSUE TITLE
`TypeError: matchPath is not a function`

### ISSUE THREAD

**Issue by RebeccaStevens** [luanglopes/ts-paths-esm-loader#14]
I get this error with the latest update (`1.4.0`). I wasn't having any issue with the previous version (`1.3.2`).

Log: https://github.com/RebeccaStevens/is-immutable-type/actions/runs/4072123978/jobs/7014570183
PR that generated log: https://github.com/RebeccaStevens/is-immutable-type/pull/38

**Comment by luanglopes** [comment]
@RebeccaStevens please, take a look at the PR, if everything looks good I will merge it and publish a new version with the fix

**Comment by RebeccaStevens** [comment]
Just tested it and it's all working for me :)
