### ISSUE TITLE
Works with yarn build + yarn start, but does not work with docker built image?

### ISSUE THREAD

**Issue by Kimblis** [luanglopes/ts-paths-esm-loader#16]
Hi, if I run `yarn build` and then `yarn start` it's succesfully starts the project, however when I build an image and then try to start it, it gives me the following error, any ideas? 
![image](https://user-images.githubusercontent.com/46688616/222920642-d1957cf4-867e-4c45-989a-ed5ffad6ca35.png)

**Comment by luanglopes** [comment]
Maybe you are not installing dev dependencies on your image building, which command are you using to install the dependencies?
